name: CyclopOne
options:
  bundleIdPrefix: com.cyclop.one
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

targets:
  CyclopOne:
    type: application
    platform: macOS
    sources:
      - path: CyclopOne
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cyclop.one.app
        PRODUCT_NAME: Cyclop One
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_ENTITLEMENTS: CyclopOne/CyclopOne.entitlements
        INFOPLIST_FILE: CyclopOne/App/Info.plist
        ENABLE_APP_SANDBOX: NO
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: CyclopOne/CyclopOne.entitlements

  CyclopOneTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: CyclopOneTests
    dependencies:
      - target: CyclopOne
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cyclop.one.tests
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Cyclop One.app/Contents/MacOS/Cyclop One"
        BUNDLE_LOADER: "$(TEST_HOST)"
